[package]
name = "beethoven"
description = "composable defi"
version = "0.1.0"
license = "MIT"
edition = "2024"

[features]
default = ["jupiter", "kamino"]
jupiter = []
kamino = []

[dependencies]
pinocchio = "0.9.2"