[target.bpfel-unknown-none]
rustflags = [
    "-C",
    "linker=sbpf-linker",
    "-C",
    "panic=abort",
    "-C",
    "save-temps",
    "-C",
    "link-arg=--llvm-args=-bpf-stack-size=4096",
    "-C",
    "relocation-model=static",
]

[alias]
build-bpf = "build -Z build-std=core,alloc --release --target bpfel-unknown-none"
